Fix/186/storage requirements
uptane/deployment-considerations pull request #95
Opened 2021-02-09 08:25 UTC by pattivacek

* Improve description of Secondaries with limited storage.
* Move section on ECUs with filesystems to the ecus page.
* Add section for non-Uptane ECUs, i.e., ECUs without secondary storage.

Related to https://github.com/uptane/uptane-standard/issues/186 and https://github.com/uptane/uptane-standard/pull/203.

2021-02-09 17:30 UTC, mnm678 approved these changes

2021-02-10 19:28 UTC, jhdalek55 requested changes
I made two small wording changes that I think make the meaning more explicit

2021-02-10 19:28 UTC, jhdalek55 commented on customizations.md
> +Finally, in order to install a delta image, an ECU SHOULD take one of the actions described in Table 1, depending on whether or not the delta image has been encrypted, and if the ECU has enough addit
```suggestion
Finally, in order to install a delta image, an ECU SHOULD take one of the actions described in Table 1, depending on whether or not the delta image has been encrypted, and if the ECU has sufficient additional storage to store a copy of the image. Note that the OEM MAY use stream ciphers in order to enable on-the-fly decryption on ECUs that do not have sufficient additional storage. In this case, the ECU would decrypt the delta image as it is downloaded, then follow the remainder of the steps in the third box.
```

2021-02-10 19:36 UTC, pattivacek commented
> I made two small wording changes that I think make the meaning more explicit

Thanks! I've merged them in.

2021-02-10 19:37 UTC, jhdalek55 approved these changes

2021-02-10 19:38 UTC, jhdalek55 commented
I'm going to merge, OK?

2021-02-10 19:43 UTC, pattivacek commented
> I'm going to merge, OK?

Gladly, thanks!

2021-02-10 19:43 UTC, merged